In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

from tensorflow.keras.preprocessing.text import one_hot

2.17.1
Num GPUs Available:  1


In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
voc_size = 500  # vocabulary size

In [11]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr) # for every word, returns the index in which it is 1

[[269, 262, 6, 259], [269, 262, 6, 325], [269, 219, 6, 487], [258, 451, 204, 388, 292], [258, 451, 204, 388, 287], [382, 269, 360, 6, 419], [497, 468, 63, 388]]


In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
max_sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=max_sent_length)  #pad zeros at front ro make size to 8
print(embedded_docs)

[[  0   0   0   0 269 262   6 259]
 [  0   0   0   0 269 262   6 325]
 [  0   0   0   0 269 219   6 487]
 [  0   0   0 258 451 204 388 292]
 [  0   0   0 258 451 204 388 287]
 [  0   0   0 382 269 360   6 419]
 [  0   0   0   0 497 468  63 388]]


In [14]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=max_sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
sent[0]

'the glass of milk'

In [21]:
embedded_docs[0]

array([  0,   0,   0,   0, 269, 262,   6, 259], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 550ms/step


array([[-0.00113721,  0.02644196, -0.03363751,  0.04469386,  0.03515733,
        -0.0264184 , -0.01910206, -0.02403972,  0.03700078,  0.01192025],
       [-0.00113721,  0.02644196, -0.03363751,  0.04469386,  0.03515733,
        -0.0264184 , -0.01910206, -0.02403972,  0.03700078,  0.01192025],
       [-0.00113721,  0.02644196, -0.03363751,  0.04469386,  0.03515733,
        -0.0264184 , -0.01910206, -0.02403972,  0.03700078,  0.01192025],
       [-0.00113721,  0.02644196, -0.03363751,  0.04469386,  0.03515733,
        -0.0264184 , -0.01910206, -0.02403972,  0.03700078,  0.01192025],
       [-0.02536651, -0.00102409, -0.02368764, -0.03895521, -0.00423714,
         0.04331282,  0.0379355 , -0.01368617, -0.04410028, -0.04945091],
       [-0.01144115, -0.04276568,  0.00674792,  0.02800522, -0.04029172,
        -0.04545312,  0.04456117, -0.03199114, -0.01894777, -0.0416426 ],
       [ 0.00608704,  0.01528889,  0.04009836, -0.03909434,  0.02138242,
         0.02375433,  0.00142226, -0.0083155 